### ISSUE TITLE
automatically send in coming emails to a specific mail folder 

### ISSUE THREAD

**Issue by joepeeer** [RapidSoftwareSolutions/Marketplace-Slack-Package#1]

**Comment by Bukati** [comment]
Can you give me more details about your issue?

**Comment by joepeeer** [comment]
yes , i would like to designate in my absence,automatically , to have certain in coming 
mail directed to a inbox of my choice.
example - so i open me mail ,i got  most mail in inbox marked as unread and a few new mail  in my designated folder . since i assigned that sender to be sent to that folder .

**Comment by Bukati** [comment]
Are you talking about specific function in this package?
Sounds like it's something you should do in you email client (Configure rules for emails).

**Comment by joepeeer** [comment]
how i do that ? have u achieved this task ?

**Comment by Bukati** [comment]
For example: https://support.google.com/mail/answer/6579?hl=en
Just Google for a tutorial if you are using a different client.
